name: Generate HTML and commit

on:
  workflow_dispatch:
    inputs:
      fileContent:
        description: 'Content for the new HTML file'     
        required: true
        default: '<h1>Hello, World!</h1>'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate HTML file
        run: |
          echo "${{ github.event.inputs.fileContent }}" > newfile.html


      - name: Commit and push if it changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add newfile.html
          git commit -m "Add generated HTML file" -a || exit 0
          git push https://${{ secrets.blog-token }}@github.com/${{ github.repository }}.git